set(_AMENT_PACKAGE_NAME "peppabot")
set(peppabot_VERSION "0.0.1")
set(peppabot_MAINTAINER "Katie E. Forster <katie.e.forster@student.uts.edu.au>")
set(peppabot_BUILD_DEPENDS "rclcpp" "geometry_msgs" "nav2_common" "nav2_msgs" "OpenCV")
set(peppabot_BUILDTOOL_DEPENDS "ament_cmake")
set(peppabot_BUILD_EXPORT_DEPENDS )
set(peppabot_BUILDTOOL_EXPORT_DEPENDS )
set(peppabot_EXEC_DEPENDS "rclcpp" "geometry_msgs" "nav2_common" "nav2_msgs" "OpenCV")
set(peppabot_TEST_DEPENDS )
set(peppabot_GROUP_DEPENDS )
set(peppabot_MEMBER_OF_GROUPS )
set(peppabot_DEPRECATED "")
set(peppabot_EXPORT_TAGS)
list(APPEND peppabot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
